import axios from "axios";
import { Response } from "../interfaces";

const http = axios.create({
  baseURL: import.meta.env.VITE_API_URL,
});

export const httpGet = async () => {
  const res = await http.get("/users");
  return res;
};

export const getCities = async () => {
  return Promise.resolve([
    {
      name: "Singapore",
      local_names: {
        et: "Singapur",
        ga: "Singeapór",
        ki: "Singapore",
        ja: "シンガポール",
        yo: "Singapore",
        kk: "Сингапур",
        tt: "Сингапур",
        da: "Singapore",
        ss: "ISingapholo",
        hi: "सिंगापुर",
        nn: "Singapore",
        ta: "சிங்கப்பூர்",
        uk: "Сінгапур",
        km: "សិង្ហបុរី",
        ff: "Sinngapuur",
        se: "Singapore",
        ka: "სინგაპური",
        tl: "Singgapur",
        es: "Singapur",
        or: "ସିଙ୍ଗାପୁର",
        hr: "Singapur",
        ne: "सिंगापुर",
        gv: "Singapore",
        li: "Singapore",
        sk: "Singapur",
        bg: "Сингапур",
        br: "Singapour",
        bi: "Singapore",
        pt: "Singapura",
        fi: "Singapore",
        sg: "Sïngäpûru",
        pa: "ਸਿੰਗਾਪੁਰ",
        am: "ሲንጋፖር",
        he: "סינגפור",
        de: "Singapur",
        su: "Singapura",
        el: "Σιγκαπούρη",
        bo: "སེང་ག་ཕོར།",
        te: "సింగపూరు",
        lb: "Singapur",
        ml: "സിംഗപ്പൂർ",
        zh: "新加坡",
        hy: "Սինգապուրի Հանրապետություն",
        mr: "सिंगापूर",
        fr: "Singapour",
        fa: "سنگاپور",
        mn: "Сингапур",
        ba: "Сингапур",
        no: "Singapore",
        my: "စင်ကာပူနိုင်ငံ",
        ko: "싱가포르",
        ar: "سنغافورة",
        id: "Singapura",
        kw: "Singapour",
        gl: "Singapur",
        ro: "Singapore",
        oc: "Singapor",
        gd: "Singeapòr",
        rw: "Singapore",
        mk: "Сингапур",
        mt: "Singapor",
        na: "Tsingapoar",
        ht: "Sengapou",
        sm: "Sigapoa",
        sa: "सिङ्गापुर",
        kl: "Singapore",
        th: "สิงคโปร์",
        fo: "Singapor",
        ie: "Singapor",
        eo: "Singapuro",
        kv: "Сингапур",
        ha: "Singapore",
        os: "Сингапур",
        be: "Сінгапур",
        sv: "Singapore",
        mg: "Singapaoro",
        lt: "Singapūras",
        az: "Sinqapur",
        ku: "Singapûr",
        dv: "ސިންގަޕޫރު",
        af: "Singapoer",
        gu: "સિંગાપુર",
        ps: "سينګاپور",
        sr: "Сингапур",
        vi: "Tân Gia Ba",
        yi: "סינגאפור",
        vo: "Singapurän",
        lv: "Singapūra",
        ur: "سنگاپور",
        ru: "Сингапур",
        so: "Singabuur",
        is: "Singapúr",
        tr: "Singapur",
        cv: "Сингапур",
        hu: "Szingapúr",
        ms: "Singapura",
        tg: "Сингапур",
        la: "Singapura",
        ug: "سىنگاپور",
        fy: "Singapore",
        it: "Singapore",
        sl: "Singapur",
        en: "Singapore",
        kn: "ಸಿಂಗಾಪುರ",
        sw: "Singapuri",
        ca: "Singapur",
        wo: "Singapoor",
        nl: "Singapore",
        jv: "Singapura",
        bn: "সিঙ্গাপুর",
        sq: "Singapori",
        mi: "Hingapoa",
        pl: "Singapur",
        cy: "Singapore",
        nv: "Sį́ʼgaboo",
        cs: "Singapur",
      },
      lat: 1.2899175,
      lon: 103.8519072,
      country: "SG",
    },
    {
      name: "Singapore",
      local_names: {
        ki: "Singapore",
        feature_name: "Singapore",
        ar: "سنغافورة",
        mt: "Singapor",
        os: "Сингапур",
        it: "Singapore",
        yi: "סינגאפור",
        ba: "Сингапур",
        hy: "Սինգապուրի Հանրապետություն",
        sq: "Singapori",
        ascii: "Singapore",
        ko: "싱가포르",
        sl: "Singapur",
        mr: "सिंगापूर",
        yo: "Singapore",
        my: "စင်ကာပူနိုင်ငံ",
        sm: "Sigapoa",
        ku: "Singapûr",
        sg: "Sïngäpûru",
        uk: "Сінгапур",
        tt: "Сингапур",
        lv: "Singapūra",
        fr: "Singapour",
        cy: "Singapore",
        kw: "Singapour",
        oc: "Singapor",
        ne: "सिंगापुर",
        br: "Singapour",
        sv: "Singapore",
        ia: "Singapur",
        fo: "Singapor",
        fy: "Singapoer",
        tr: "Singapur",
        no: "Singapore",
        wo: "Singapoor",
        sh: "Singapur",
        he: "סינגפור",
        ht: "Sengapou",
        te: "సింగపూరు",
        dv: "ސިންގަޕޫރު",
        hr: "Singapur",
        gd: "Singeapòr",
        ja: "シンガポール",
        nl: "Singapore",
        sr: "Сингапур",
        mk: "Сингапур",
        fi: "Singapore",
        la: "Singapura",
        en: "Singapore",
        vi: "Singapore",
        ro: "Singapore",
        lt: "Singapūras",
        mn: "Сингапур",
        io: "Singapur",
        gu: "સિંગાપુર",
        kv: "Сингапур",
        se: "Singapore",
        bg: "Сингапур",
        ta: "சிங்கப்பூர்",
        bi: "Singapore",
        be: "Сінгапур",
        lb: "Singapur",
        af: "Singapoer",
        ss: "ISingapholo",
        km: "សិង្ហបុរី",
        uz: "Singapur",
        eo: "Singapuro",
        fa: "سنگاپور",
        tg: "Сингапур",
        es: "Singapur",
        sa: "सिङ्गापुरम्",
        cs: "Singapur",
        kk: "Сингапур",
        ru: "Сингапур",
        tk: "Singapur",
        ur: "سنگاپور",
        ka: "სინგაპური",
        th: "ประเทศสิงคโปร์",
        zh: "新加坡",
        is: "Singapúr",
        ml: "സിംഗപ്പൂർ",
        ug: "سىنگاپور",
        ie: "Singapor",
        nn: "Singapore",
        tl: "Singapore",
        kn: "ಸಿಂಗಾಪುರ್",
        kl: "Singapore",
        hi: "सिंगापुर",
        ha: "Singapore",
        ca: "Singapur",
        et: "Singapur",
        gv: "Singapore",
        ky: "Сингапур",
        da: "Singapore",
        pa: "ਸਿੰਘਾਪੁਰ",
        sw: "Singapuri",
        bs: "Singapur",
        ga: "Singeapór",
        sk: "Singapur",
        su: "Singapura",
        ms: "Singapura",
        an: "Singapur",
        bn: "সিঙ্গাপুর",
        or: "ସିଙ୍ଗାପୁର",
        hu: "Szingapúr",
        cv: "Сингапур",
        mg: "Singapaoro",
        id: "Singapura",
        gl: "Singapur",
        vo: "Singapurän",
        jv: "Singapura",
        rw: "Singapore",
        ps: "سينګاپور",
        pt: "Singapura",
        li: "Singapore",
        ce: "Сингапур",
        ff: "Sinngapuur",
        ln: "Singapur",
        am: "ሲንጋፖር",
        eu: "Singapur",
        mi: "Hingapoa",
        bo: "སེང་ག་ཕོར།",
        el: "Σιγκαπούρη",
        qu: "Singapur",
        pl: "Singapur",
        de: "Singapur",
        so: "Singabuur",
        na: "Tsingapoar",
        az: "Sinqapur",
        nv: "Sį́ʼgaboo",
      },
      lat: 1.340863,
      lon: 103.830391822121,
      country: "SG",
    },
    {
      name: "Singapore",
      lat: 60.16544905,
      lon: 13.7420508047613,
      country: "SE",
    },
    {
      name: "Singapore",
      lat: -29.6632273,
      lon: 150.4151121,
      country: "AU",
      state: "New South Wales",
    },
  ]);
};

export const getData = async (): Promise<Response> => {
  return Promise.resolve({
    cod: "200",
    message: 0,
    cnt: 40,
    list: [
      {
        dt: 1744135200,
        main: {
          temp: 26.47,
          feels_like: 26.47,
          temp_min: 26.47,
          temp_max: 26.78,
          pressure: 1011,
          sea_level: 1011,
          grnd_level: 1010,
          humidity: 87,
          temp_kf: -0.31,
        },
        weather: [
          {
            id: 803,
            main: "Clouds",
            description: "broken clouds",
            icon: "04n",
          },
        ],
        clouds: {
          all: 75,
        },
        wind: {
          speed: 4.09,
          deg: 35,
          gust: 4.93,
        },
        visibility: 10000,
        pop: 0,
        sys: {
          pod: "n",
        },
        dt_txt: "2025-04-08 18:00:00",
      },
      {
        dt: 1744146000,
        main: {
          temp: 26.52,
          feels_like: 26.52,
          temp_min: 26.52,
          temp_max: 26.63,
          pressure: 1011,
          sea_level: 1011,
          grnd_level: 1009,
          humidity: 86,
          temp_kf: -0.11,
        },
        weather: [
          {
            id: 500,
            main: "Rain",
            description: "light rain",
            icon: "10n",
          },
        ],
        clouds: {
          all: 80,
        },
        wind: {
          speed: 3.9,
          deg: 17,
          gust: 4.69,
        },
        visibility: 10000,
        pop: 0.81,
        rain: {
          "3h": 0.74,
        },
        sys: {
          pod: "n",
        },
        dt_txt: "2025-04-08 21:00:00",
      },
      {
        dt: 1744156800,
        main: {
          temp: 26.87,
          feels_like: 29.9,
          temp_min: 26.87,
          temp_max: 27.07,
          pressure: 1011,
          sea_level: 1011,
          grnd_level: 1011,
          humidity: 85,
          temp_kf: -0.2,
        },
        weather: [
          {
            id: 500,
            main: "Rain",
            description: "light rain",
            icon: "10d",
          },
        ],
        clouds: {
          all: 83,
        },
        wind: {
          speed: 2.89,
          deg: 7,
          gust: 2.99,
        },
        visibility: 10000,
        pop: 0.64,
        rain: {
          "3h": 0.2,
        },
        sys: {
          pod: "d",
        },
        dt_txt: "2025-04-09 00:00:00",
      },
      {
        dt: 1744167600,
        main: {
          temp: 29.52,
          feels_like: 34.33,
          temp_min: 29.52,
          temp_max: 29.52,
          pressure: 1012,
          sea_level: 1012,
          grnd_level: 1011,
          humidity: 72,
          temp_kf: 0,
        },
        weather: [
          {
            id: 500,
            main: "Rain",
            description: "light rain",
            icon: "10d",
          },
        ],
        clouds: {
          all: 34,
        },
        wind: {
          speed: 1.38,
          deg: 44,
          gust: 1.61,
        },
        visibility: 10000,
        pop: 0.91,
        rain: {
          "3h": 0.61,
        },
        sys: {
          pod: "d",
        },
        dt_txt: "2025-04-09 03:00:00",
      },
      {
        dt: 1744178400,
        main: {
          temp: 28.38,
          feels_like: 31.89,
          temp_min: 28.38,
          temp_max: 28.38,
          pressure: 1009,
          sea_level: 1009,
          grnd_level: 1009,
          humidity: 73,
          temp_kf: 0,
        },
        weather: [
          {
            id: 500,
            main: "Rain",
            description: "light rain",
            icon: "10d",
          },
        ],
        clouds: {
          all: 37,
        },
        wind: {
          speed: 2.15,
          deg: 157,
          gust: 1.97,
        },
        visibility: 10000,
        pop: 0.99,
        rain: {
          "3h": 0.57,
        },
        sys: {
          pod: "d",
        },
        dt_txt: "2025-04-09 06:00:00",
      },
      {
        dt: 1744189200,
        main: {
          temp: 28.25,
          feels_like: 31.45,
          temp_min: 28.25,
          temp_max: 28.25,
          pressure: 1007,
          sea_level: 1007,
          grnd_level: 1007,
          humidity: 72,
          temp_kf: 0,
        },
        weather: [
          {
            id: 500,
            main: "Rain",
            description: "light rain",
            icon: "10d",
          },
        ],
        clouds: {
          all: 27,
        },
        wind: {
          speed: 2.07,
          deg: 110,
          gust: 2.25,
        },
        visibility: 10000,
        pop: 0.93,
        rain: {
          "3h": 1.12,
        },
        sys: {
          pod: "d",
        },
        dt_txt: "2025-04-09 09:00:00",
      },
      {
        dt: 1744200000,
        main: {
          temp: 28.15,
          feels_like: 32.48,
          temp_min: 28.15,
          temp_max: 28.15,
          pressure: 1010,
          sea_level: 1010,
          grnd_level: 1009,
          humidity: 80,
          temp_kf: 0,
        },
        weather: [
          {
            id: 500,
            main: "Rain",
            description: "light rain",
            icon: "10n",
          },
        ],
        clouds: {
          all: 49,
        },
        wind: {
          speed: 4.73,
          deg: 64,
          gust: 5.31,
        },
        visibility: 10000,
        pop: 0.97,
        rain: {
          "3h": 0.72,
        },
        sys: {
          pod: "n",
        },
        dt_txt: "2025-04-09 12:00:00",
      },
      {
        dt: 1744210800,
        main: {
          temp: 27.64,
          feels_like: 31.22,
          temp_min: 27.64,
          temp_max: 27.64,
          pressure: 1011,
          sea_level: 1011,
          grnd_level: 1010,
          humidity: 80,
          temp_kf: 0,
        },
        weather: [
          {
            id: 803,
            main: "Clouds",
            description: "broken clouds",
            icon: "04n",
          },
        ],
        clouds: {
          all: 84,
        },
        wind: {
          speed: 3.07,
          deg: 54,
          gust: 3.41,
        },
        visibility: 10000,
        pop: 0,
        sys: {
          pod: "n",
        },
        dt_txt: "2025-04-09 15:00:00",
      },
      {
        dt: 1744221600,
        main: {
          temp: 27.18,
          feels_like: 30.14,
          temp_min: 27.18,
          temp_max: 27.18,
          pressure: 1009,
          sea_level: 1009,
          grnd_level: 1008,
          humidity: 80,
          temp_kf: 0,
        },
        weather: [
          {
            id: 803,
            main: "Clouds",
            description: "broken clouds",
            icon: "04n",
          },
        ],
        clouds: {
          all: 80,
        },
        wind: {
          speed: 1.84,
          deg: 75,
          gust: 1.84,
        },
        visibility: 10000,
        pop: 0,
        sys: {
          pod: "n",
        },
        dt_txt: "2025-04-09 18:00:00",
      },
      {
        dt: 1744232400,
        main: {
          temp: 26.96,
          feels_like: 29.65,
          temp_min: 26.96,
          temp_max: 26.96,
          pressure: 1008,
          sea_level: 1008,
          grnd_level: 1007,
          humidity: 80,
          temp_kf: 0,
        },
        weather: [
          {
            id: 500,
            main: "Rain",
            description: "light rain",
            icon: "10n",
          },
        ],
        clouds: {
          all: 79,
        },
        wind: {
          speed: 0.24,
          deg: 300,
          gust: 0.28,
        },
        visibility: 10000,
        pop: 0.32,
        rain: {
          "3h": 0.2,
        },
        sys: {
          pod: "n",
        },
        dt_txt: "2025-04-09 21:00:00",
      },
      {
        dt: 1744243200,
        main: {
          temp: 26.98,
          feels_like: 29.6,
          temp_min: 26.98,
          temp_max: 26.98,
          pressure: 1010,
          sea_level: 1010,
          grnd_level: 1009,
          humidity: 79,
          temp_kf: 0,
        },
        weather: [
          {
            id: 500,
            main: "Rain",
            description: "light rain",
            icon: "10d",
          },
        ],
        clouds: {
          all: 87,
        },
        wind: {
          speed: 0.42,
          deg: 280,
          gust: 0.7,
        },
        visibility: 10000,
        pop: 0.61,
        rain: {
          "3h": 0.99,
        },
        sys: {
          pod: "d",
        },
        dt_txt: "2025-04-10 00:00:00",
      },
      {
        dt: 1744254000,
        main: {
          temp: 27.9,
          feels_like: 31.14,
          temp_min: 27.9,
          temp_max: 27.9,
          pressure: 1011,
          sea_level: 1011,
          grnd_level: 1010,
          humidity: 75,
          temp_kf: 0,
        },
        weather: [
          {
            id: 804,
            main: "Clouds",
            description: "overcast clouds",
            icon: "04d",
          },
        ],
        clouds: {
          all: 100,
        },
        wind: {
          speed: 2.78,
          deg: 219,
          gust: 2.89,
        },
        visibility: 10000,
        pop: 0.01,
        sys: {
          pod: "d",
        },
        dt_txt: "2025-04-10 03:00:00",
      },
      {
        dt: 1744264800,
        main: {
          temp: 27.43,
          feels_like: 30.6,
          temp_min: 27.43,
          temp_max: 27.43,
          pressure: 1008,
          sea_level: 1008,
          grnd_level: 1007,
          humidity: 79,
          temp_kf: 0,
        },
        weather: [
          {
            id: 500,
            main: "Rain",
            description: "light rain",
            icon: "10d",
          },
        ],
        clouds: {
          all: 96,
        },
        wind: {
          speed: 4,
          deg: 230,
          gust: 3.61,
        },
        visibility: 10000,
        pop: 0.3,
        rain: {
          "3h": 0.23,
        },
        sys: {
          pod: "d",
        },
        dt_txt: "2025-04-10 06:00:00",
      },
      {
        dt: 1744275600,
        main: {
          temp: 27.99,
          feels_like: 31.19,
          temp_min: 27.99,
          temp_max: 27.99,
          pressure: 1006,
          sea_level: 1006,
          grnd_level: 1005,
          humidity: 74,
          temp_kf: 0,
        },
        weather: [
          {
            id: 803,
            main: "Clouds",
            description: "broken clouds",
            icon: "04d",
          },
        ],
        clouds: {
          all: 71,
        },
        wind: {
          speed: 3.7,
          deg: 246,
          gust: 3.55,
        },
        visibility: 10000,
        pop: 0.29,
        sys: {
          pod: "d",
        },
        dt_txt: "2025-04-10 09:00:00",
      },
      {
        dt: 1744286400,
        main: {
          temp: 28.37,
          feels_like: 31.87,
          temp_min: 28.37,
          temp_max: 28.37,
          pressure: 1008,
          sea_level: 1008,
          grnd_level: 1007,
          humidity: 73,
          temp_kf: 0,
        },
        weather: [
          {
            id: 804,
            main: "Clouds",
            description: "overcast clouds",
            icon: "04n",
          },
        ],
        clouds: {
          all: 85,
        },
        wind: {
          speed: 1.15,
          deg: 257,
          gust: 1.25,
        },
        visibility: 10000,
        pop: 0.17,
        sys: {
          pod: "n",
        },
        dt_txt: "2025-04-10 12:00:00",
      },
      {
        dt: 1744297200,
        main: {
          temp: 28.14,
          feels_like: 31.82,
          temp_min: 28.14,
          temp_max: 28.14,
          pressure: 1009,
          sea_level: 1009,
          grnd_level: 1008,
          humidity: 76,
          temp_kf: 0,
        },
        weather: [
          {
            id: 804,
            main: "Clouds",
            description: "overcast clouds",
            icon: "04n",
          },
        ],
        clouds: {
          all: 94,
        },
        wind: {
          speed: 0.74,
          deg: 189,
          gust: 1.09,
        },
        visibility: 10000,
        pop: 0,
        sys: {
          pod: "n",
        },
        dt_txt: "2025-04-10 15:00:00",
      },
      {
        dt: 1744308000,
        main: {
          temp: 27.8,
          feels_like: 30.92,
          temp_min: 27.8,
          temp_max: 27.8,
          pressure: 1008,
          sea_level: 1008,
          grnd_level: 1007,
          humidity: 75,
          temp_kf: 0,
        },
        weather: [
          {
            id: 803,
            main: "Clouds",
            description: "broken clouds",
            icon: "04n",
          },
        ],
        clouds: {
          all: 78,
        },
        wind: {
          speed: 0.52,
          deg: 322,
          gust: 1,
        },
        visibility: 10000,
        pop: 0,
        sys: {
          pod: "n",
        },
        dt_txt: "2025-04-10 18:00:00",
      },
      {
        dt: 1744318800,
        main: {
          temp: 27.37,
          feels_like: 30.24,
          temp_min: 27.37,
          temp_max: 27.37,
          pressure: 1007,
          sea_level: 1007,
          grnd_level: 1006,
          humidity: 77,
          temp_kf: 0,
        },
        weather: [
          {
            id: 804,
            main: "Clouds",
            description: "overcast clouds",
            icon: "04n",
          },
        ],
        clouds: {
          all: 85,
        },
        wind: {
          speed: 1.43,
          deg: 320,
          gust: 1.64,
        },
        visibility: 10000,
        pop: 0,
        sys: {
          pod: "n",
        },
        dt_txt: "2025-04-10 21:00:00",
      },
      {
        dt: 1744329600,
        main: {
          temp: 27.04,
          feels_like: 29.73,
          temp_min: 27.04,
          temp_max: 27.04,
          pressure: 1009,
          sea_level: 1009,
          grnd_level: 1008,
          humidity: 79,
          temp_kf: 0,
        },
        weather: [
          {
            id: 500,
            main: "Rain",
            description: "light rain",
            icon: "10d",
          },
        ],
        clouds: {
          all: 92,
        },
        wind: {
          speed: 1.11,
          deg: 318,
          gust: 1.34,
        },
        visibility: 10000,
        pop: 0.74,
        rain: {
          "3h": 0.57,
        },
        sys: {
          pod: "d",
        },
        dt_txt: "2025-04-11 00:00:00",
      },
      {
        dt: 1744340400,
        main: {
          temp: 28.44,
          feels_like: 32.02,
          temp_min: 28.44,
          temp_max: 28.44,
          pressure: 1010,
          sea_level: 1010,
          grnd_level: 1010,
          humidity: 73,
          temp_kf: 0,
        },
        weather: [
          {
            id: 500,
            main: "Rain",
            description: "light rain",
            icon: "10d",
          },
        ],
        clouds: {
          all: 96,
        },
        wind: {
          speed: 4.04,
          deg: 263,
          gust: 4.49,
        },
        visibility: 10000,
        pop: 0.93,
        rain: {
          "3h": 1.05,
        },
        sys: {
          pod: "d",
        },
        dt_txt: "2025-04-11 03:00:00",
      },
      {
        dt: 1744351200,
        main: {
          temp: 28.61,
          feels_like: 32.4,
          temp_min: 28.61,
          temp_max: 28.61,
          pressure: 1008,
          sea_level: 1008,
          grnd_level: 1007,
          humidity: 73,
          temp_kf: 0,
        },
        weather: [
          {
            id: 500,
            main: "Rain",
            description: "light rain",
            icon: "10d",
          },
        ],
        clouds: {
          all: 98,
        },
        wind: {
          speed: 6.05,
          deg: 250,
          gust: 6.49,
        },
        visibility: 10000,
        pop: 1,
        rain: {
          "3h": 2.82,
        },
        sys: {
          pod: "d",
        },
        dt_txt: "2025-04-11 06:00:00",
      },
      {
        dt: 1744362000,
        main: {
          temp: 28.8,
          feels_like: 33.02,
          temp_min: 28.8,
          temp_max: 28.8,
          pressure: 1006,
          sea_level: 1006,
          grnd_level: 1006,
          humidity: 74,
          temp_kf: 0,
        },
        weather: [
          {
            id: 500,
            main: "Rain",
            description: "light rain",
            icon: "10d",
          },
        ],
        clouds: {
          all: 56,
        },
        wind: {
          speed: 6.27,
          deg: 258,
          gust: 6.87,
        },
        visibility: 10000,
        pop: 0.45,
        rain: {
          "3h": 0.21,
        },
        sys: {
          pod: "d",
        },
        dt_txt: "2025-04-11 09:00:00",
      },
      {
        dt: 1744372800,
        main: {
          temp: 27.91,
          feels_like: 31.88,
          temp_min: 27.91,
          temp_max: 27.91,
          pressure: 1008,
          sea_level: 1008,
          grnd_level: 1007,
          humidity: 80,
          temp_kf: 0,
        },
        weather: [
          {
            id: 500,
            main: "Rain",
            description: "light rain",
            icon: "10n",
          },
        ],
        clouds: {
          all: 68,
        },
        wind: {
          speed: 6.3,
          deg: 281,
          gust: 9.24,
        },
        visibility: 10000,
        pop: 0.86,
        rain: {
          "3h": 1.28,
        },
        sys: {
          pod: "n",
        },
        dt_txt: "2025-04-11 12:00:00",
      },
      {
        dt: 1744383600,
        main: {
          temp: 27.66,
          feels_like: 31.4,
          temp_min: 27.66,
          temp_max: 27.66,
          pressure: 1010,
          sea_level: 1010,
          grnd_level: 1009,
          humidity: 81,
          temp_kf: 0,
        },
        weather: [
          {
            id: 500,
            main: "Rain",
            description: "light rain",
            icon: "10n",
          },
        ],
        clouds: {
          all: 45,
        },
        wind: {
          speed: 4.85,
          deg: 293,
          gust: 7.11,
        },
        visibility: 10000,
        pop: 0.93,
        rain: {
          "3h": 1.67,
        },
        sys: {
          pod: "n",
        },
        dt_txt: "2025-04-11 15:00:00",
      },
      {
        dt: 1744394400,
        main: {
          temp: 26.88,
          feels_like: 29.74,
          temp_min: 26.88,
          temp_max: 26.88,
          pressure: 1008,
          sea_level: 1008,
          grnd_level: 1008,
          humidity: 83,
          temp_kf: 0,
        },
        weather: [
          {
            id: 500,
            main: "Rain",
            description: "light rain",
            icon: "10n",
          },
        ],
        clouds: {
          all: 68,
        },
        wind: {
          speed: 3.65,
          deg: 332,
          gust: 4.28,
        },
        visibility: 10000,
        pop: 0.81,
        rain: {
          "3h": 0.37,
        },
        sys: {
          pod: "n",
        },
        dt_txt: "2025-04-11 18:00:00",
      },
      {
        dt: 1744405200,
        main: {
          temp: 26.66,
          feels_like: 26.66,
          temp_min: 26.66,
          temp_max: 26.66,
          pressure: 1008,
          sea_level: 1008,
          grnd_level: 1007,
          humidity: 82,
          temp_kf: 0,
        },
        weather: [
          {
            id: 804,
            main: "Clouds",
            description: "overcast clouds",
            icon: "04n",
          },
        ],
        clouds: {
          all: 94,
        },
        wind: {
          speed: 2.73,
          deg: 356,
          gust: 3.03,
        },
        visibility: 10000,
        pop: 0.39,
        sys: {
          pod: "n",
        },
        dt_txt: "2025-04-11 21:00:00",
      },
      {
        dt: 1744416000,
        main: {
          temp: 26.69,
          feels_like: 29.22,
          temp_min: 26.69,
          temp_max: 26.69,
          pressure: 1009,
          sea_level: 1009,
          grnd_level: 1009,
          humidity: 82,
          temp_kf: 0,
        },
        weather: [
          {
            id: 500,
            main: "Rain",
            description: "light rain",
            icon: "10d",
          },
        ],
        clouds: {
          all: 97,
        },
        wind: {
          speed: 3.57,
          deg: 347,
          gust: 3.84,
        },
        visibility: 10000,
        pop: 0.74,
        rain: {
          "3h": 1.43,
        },
        sys: {
          pod: "d",
        },
        dt_txt: "2025-04-12 00:00:00",
      },
      {
        dt: 1744426800,
        main: {
          temp: 27.88,
          feels_like: 30.96,
          temp_min: 27.88,
          temp_max: 27.88,
          pressure: 1011,
          sea_level: 1011,
          grnd_level: 1010,
          humidity: 74,
          temp_kf: 0,
        },
        weather: [
          {
            id: 501,
            main: "Rain",
            description: "moderate rain",
            icon: "10d",
          },
        ],
        clouds: {
          all: 100,
        },
        wind: {
          speed: 1.75,
          deg: 322,
          gust: 2.1,
        },
        visibility: 10000,
        pop: 1,
        rain: {
          "3h": 3.25,
        },
        sys: {
          pod: "d",
        },
        dt_txt: "2025-04-12 03:00:00",
      },
      {
        dt: 1744437600,
        main: {
          temp: 28.41,
          feels_like: 31.79,
          temp_min: 28.41,
          temp_max: 28.41,
          pressure: 1008,
          sea_level: 1008,
          grnd_level: 1008,
          humidity: 72,
          temp_kf: 0,
        },
        weather: [
          {
            id: 501,
            main: "Rain",
            description: "moderate rain",
            icon: "10d",
          },
        ],
        clouds: {
          all: 81,
        },
        wind: {
          speed: 2.34,
          deg: 268,
          gust: 2.54,
        },
        visibility: 10000,
        pop: 1,
        rain: {
          "3h": 3.23,
        },
        sys: {
          pod: "d",
        },
        dt_txt: "2025-04-12 06:00:00",
      },
      {
        dt: 1744448400,
        main: {
          temp: 28.4,
          feels_like: 31.93,
          temp_min: 28.4,
          temp_max: 28.4,
          pressure: 1007,
          sea_level: 1007,
          grnd_level: 1006,
          humidity: 73,
          temp_kf: 0,
        },
        weather: [
          {
            id: 501,
            main: "Rain",
            description: "moderate rain",
            icon: "10d",
          },
        ],
        clouds: {
          all: 69,
        },
        wind: {
          speed: 2.73,
          deg: 264,
          gust: 2.74,
        },
        visibility: 10000,
        pop: 1,
        rain: {
          "3h": 3.58,
        },
        sys: {
          pod: "d",
        },
        dt_txt: "2025-04-12 09:00:00",
      },
      {
        dt: 1744459200,
        main: {
          temp: 27.74,
          feels_like: 30.92,
          temp_min: 27.74,
          temp_max: 27.74,
          pressure: 1009,
          sea_level: 1009,
          grnd_level: 1008,
          humidity: 76,
          temp_kf: 0,
        },
        weather: [
          {
            id: 501,
            main: "Rain",
            description: "moderate rain",
            icon: "10n",
          },
        ],
        clouds: {
          all: 66,
        },
        wind: {
          speed: 1.94,
          deg: 36,
          gust: 2.05,
        },
        visibility: 10000,
        pop: 1,
        rain: {
          "3h": 4.15,
        },
        sys: {
          pod: "n",
        },
        dt_txt: "2025-04-12 12:00:00",
      },
      {
        dt: 1744470000,
        main: {
          temp: 27.67,
          feels_like: 31.03,
          temp_min: 27.67,
          temp_max: 27.67,
          pressure: 1011,
          sea_level: 1011,
          grnd_level: 1010,
          humidity: 78,
          temp_kf: 0,
        },
        weather: [
          {
            id: 500,
            main: "Rain",
            description: "light rain",
            icon: "10n",
          },
        ],
        clouds: {
          all: 41,
        },
        wind: {
          speed: 2.67,
          deg: 34,
          gust: 2.8,
        },
        visibility: 10000,
        pop: 0.65,
        rain: {
          "3h": 0.64,
        },
        sys: {
          pod: "n",
        },
        dt_txt: "2025-04-12 15:00:00",
      },
      {
        dt: 1744480800,
        main: {
          temp: 26.97,
          feels_like: 29.67,
          temp_min: 26.97,
          temp_max: 26.97,
          pressure: 1009,
          sea_level: 1009,
          grnd_level: 1008,
          humidity: 80,
          temp_kf: 0,
        },
        weather: [
          {
            id: 500,
            main: "Rain",
            description: "light rain",
            icon: "10n",
          },
        ],
        clouds: {
          all: 30,
        },
        wind: {
          speed: 3.32,
          deg: 23,
          gust: 3.38,
        },
        visibility: 10000,
        pop: 0.64,
        rain: {
          "3h": 0.31,
        },
        sys: {
          pod: "n",
        },
        dt_txt: "2025-04-12 18:00:00",
      },
      {
        dt: 1744491600,
        main: {
          temp: 26.47,
          feels_like: 26.47,
          temp_min: 26.47,
          temp_max: 26.47,
          pressure: 1009,
          sea_level: 1009,
          grnd_level: 1008,
          humidity: 81,
          temp_kf: 0,
        },
        weather: [
          {
            id: 500,
            main: "Rain",
            description: "light rain",
            icon: "10n",
          },
        ],
        clouds: {
          all: 43,
        },
        wind: {
          speed: 2.9,
          deg: 10,
          gust: 3.01,
        },
        visibility: 10000,
        pop: 0.33,
        rain: {
          "3h": 0.25,
        },
        sys: {
          pod: "n",
        },
        dt_txt: "2025-04-12 21:00:00",
      },
      {
        dt: 1744502400,
        main: {
          temp: 26.43,
          feels_like: 26.43,
          temp_min: 26.43,
          temp_max: 26.43,
          pressure: 1010,
          sea_level: 1010,
          grnd_level: 1010,
          humidity: 82,
          temp_kf: 0,
        },
        weather: [
          {
            id: 500,
            main: "Rain",
            description: "light rain",
            icon: "10d",
          },
        ],
        clouds: {
          all: 67,
        },
        wind: {
          speed: 3.18,
          deg: 26,
          gust: 3.48,
        },
        visibility: 10000,
        pop: 0.48,
        rain: {
          "3h": 0.41,
        },
        sys: {
          pod: "d",
        },
        dt_txt: "2025-04-13 00:00:00",
      },
      {
        dt: 1744513200,
        main: {
          temp: 28.18,
          feels_like: 31.16,
          temp_min: 28.18,
          temp_max: 28.18,
          pressure: 1011,
          sea_level: 1011,
          grnd_level: 1011,
          humidity: 71,
          temp_kf: 0,
        },
        weather: [
          {
            id: 500,
            main: "Rain",
            description: "light rain",
            icon: "10d",
          },
        ],
        clouds: {
          all: 70,
        },
        wind: {
          speed: 0.87,
          deg: 15,
          gust: 1.19,
        },
        visibility: 10000,
        pop: 0.67,
        rain: {
          "3h": 0.35,
        },
        sys: {
          pod: "d",
        },
        dt_txt: "2025-04-13 03:00:00",
      },
      {
        dt: 1744524000,
        main: {
          temp: 28.25,
          feels_like: 31.45,
          temp_min: 28.25,
          temp_max: 28.25,
          pressure: 1009,
          sea_level: 1009,
          grnd_level: 1008,
          humidity: 72,
          temp_kf: 0,
        },
        weather: [
          {
            id: 500,
            main: "Rain",
            description: "light rain",
            icon: "10d",
          },
        ],
        clouds: {
          all: 61,
        },
        wind: {
          speed: 2.98,
          deg: 260,
          gust: 2.98,
        },
        visibility: 10000,
        pop: 1,
        rain: {
          "3h": 2.6,
        },
        sys: {
          pod: "d",
        },
        dt_txt: "2025-04-13 06:00:00",
      },
      {
        dt: 1744534800,
        main: {
          temp: 28.02,
          feels_like: 31.4,
          temp_min: 28.02,
          temp_max: 28.02,
          pressure: 1008,
          sea_level: 1008,
          grnd_level: 1007,
          humidity: 75,
          temp_kf: 0,
        },
        weather: [
          {
            id: 501,
            main: "Rain",
            description: "moderate rain",
            icon: "10d",
          },
        ],
        clouds: {
          all: 78,
        },
        wind: {
          speed: 4.72,
          deg: 264,
          gust: 5.38,
        },
        visibility: 10000,
        pop: 1,
        rain: {
          "3h": 4.38,
        },
        sys: {
          pod: "d",
        },
        dt_txt: "2025-04-13 09:00:00",
      },
      {
        dt: 1744545600,
        main: {
          temp: 27.42,
          feels_like: 30.7,
          temp_min: 27.42,
          temp_max: 27.42,
          pressure: 1009,
          sea_level: 1009,
          grnd_level: 1009,
          humidity: 80,
          temp_kf: 0,
        },
        weather: [
          {
            id: 501,
            main: "Rain",
            description: "moderate rain",
            icon: "10n",
          },
        ],
        clouds: {
          all: 92,
        },
        wind: {
          speed: 5.65,
          deg: 294,
          gust: 8.94,
        },
        visibility: 6665,
        pop: 1,
        rain: {
          "3h": 6.84,
        },
        sys: {
          pod: "n",
        },
        dt_txt: "2025-04-13 12:00:00",
      },
      {
        dt: 1744556400,
        main: {
          temp: 25.66,
          feels_like: 26.58,
          temp_min: 25.66,
          temp_max: 25.66,
          pressure: 1011,
          sea_level: 1011,
          grnd_level: 1010,
          humidity: 88,
          temp_kf: 0,
        },
        weather: [
          {
            id: 500,
            main: "Rain",
            description: "light rain",
            icon: "10n",
          },
        ],
        clouds: {
          all: 98,
        },
        wind: {
          speed: 6.51,
          deg: 302,
          gust: 8.63,
        },
        visibility: 10000,
        pop: 1,
        rain: {
          "3h": 0.99,
        },
        sys: {
          pod: "n",
        },
        dt_txt: "2025-04-13 15:00:00",
      },
    ],
    city: {
      id: 1880252,
      name: "Singapore",
      coord: {
        lat: 1.2899,
        lon: 103.8519,
      },
      country: "SG",
      population: 3547809,
      timezone: 28800,
      sunrise: 1744153318,
      sunset: 1744197003,
    },
  });
};

export const getImage = (code: string) => {
  return `https://openweathermap.org/img/wn/${code}@2x.png`;
};
